# Application services - Gateway, Bridge, Indexer
# Usage: docker compose -f compose.base.yml -f compose.services.yml up -d

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: gateway
    container_name: gateway
    restart: unless-stopped
    ports:
      - "${GATEWAY_PORT:-4000}:4000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-ottochain}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-ottochain}
      REDIS_URL: redis://redis:6379
      METAGRAPH_ML0_URL: ${METAGRAPH_ML0_URL:-http://host.docker.internal:9100}
      METAGRAPH_DL1_URL: ${METAGRAPH_DL1_URL:-http://host.docker.internal:9400}
      GATEWAY_PORT: 4000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ottochain

  bridge:
    build:
      context: .
      dockerfile: Dockerfile
      target: bridge
    container_name: bridge
    restart: unless-stopped
    ports:
      - "${BRIDGE_PORT:-3030}:3030"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-ottochain}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-ottochain}
      REDIS_URL: redis://redis:6379
      METAGRAPH_ML0_URL: ${METAGRAPH_ML0_URL:-http://host.docker.internal:9100}
      METAGRAPH_DL1_URL: ${METAGRAPH_DL1_URL:-http://host.docker.internal:9400}
      BRIDGE_PORT: 3030
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ottochain

  indexer:
    build:
      context: .
      dockerfile: Dockerfile
      target: indexer
    container_name: indexer
    restart: unless-stopped
    ports:
      - "${INDEXER_PORT:-3031}:3031"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-ottochain}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-ottochain}
      REDIS_URL: redis://redis:6379
      METAGRAPH_ML0_URL: ${METAGRAPH_ML0_URL:-http://host.docker.internal:9100}
      METAGRAPH_DL1_URL: ${METAGRAPH_DL1_URL:-http://host.docker.internal:9400}
      INDEXER_PORT: 3031
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ottochain

networks:
  ottochain:
    external: true
