#!/usr/bin/env bash
# Generate version info and write to .env.version
# Source this file or export the vars before starting services

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Get git info
GIT_SHA=$(git -C "$PROJECT_ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_BRANCH=$(git -C "$PROJECT_ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Get version from package.json
VERSION=$(node -p "require('$PROJECT_ROOT/package.json').version" 2>/dev/null || echo "0.0.0")

# Write to .env.version file
cat > "$PROJECT_ROOT/.env.version" << EOF
# Auto-generated by build-version.sh - do not edit
GIT_SHA=$GIT_SHA
GIT_BRANCH=$GIT_BRANCH
BUILD_TIME=$BUILD_TIME
VERSION=$VERSION
EOF

echo "Version info written to .env.version:"
cat "$PROJECT_ROOT/.env.version"

# Also export for current shell
export GIT_SHA GIT_BRANCH BUILD_TIME VERSION
